### PR TITLE
Add tldr as recommended command line tool

### PR DESCRIPTION
**Pull request by ralren**
What the title says.

### CODE REVIEW

**Comment by nelztruss** [comment]
@ralren Did a linter change all the "*" to "-"? Was that intentional?

**Comment by ralren** [comment]
@nelztruss not intentional. Must have been a linter.

**Comment by nelztruss** [comment]
@ralren So, I'm not sure how process-y we should be in this repo. Usually, it's considered to be a good idea to break up substantive changes from formatting changes into different commits. (Also, it'd probably be a good idea to figure out why the linter all of a sudden changed its mind on "-" vs "*" for bullets, was it because of a newly release version or something?)
I'll give you the thumbs-up so you can commit if you don't feel that these suggestions are germane for this project.

**Comment by ralren** [comment]
@nelztruss, I'll at least spend fifteen minutes debugging what's going on with the linter.

**Pull request merged**
