### PR TITLE
update lint install

### PR DESCRIPTION
**Pull request by nelztruss**
Install for `markdownlint` is via `npm` as per https://github.com/igorshubovych/markdownlint-cli (rather than via `brew`)

### CODE REVIEW

**Comment by brainsik** [comment]
You don't need to install _any_ version of markdownlint. This should be handled by `pre-commit` itself. In general, that's how `pre-commit` works. There are some exceptions where you do need to install an external binary (e.g., `terraform` and `shellcheck`) in order for the hook to do it's thing, but that's not the general case.

**Comment by nelztruss** [comment]
Changed the PR to remove the errant instruction:
```
$ brew install markdownlint
Error: No available formula with the name "markdownlint"
```

**Comment by monfresh** [comment]
Can we squash the commits before merging, please, so it's clearer what the issue was?

**Comment by nelztruss** [comment]
Slack discussion: https://trussworks.slack.com/archives/CDJ9JAD26/p1570054331253700

**Pull request merged**
