### PR TITLE
Remove custom TOC from markdown

### LINKED ISSUE #254: Remove custom Table of Content sections
The markdown pages in this repository post the Docusaurus migration contain comments with `mdformat-toc start`. These are no longer relevant as Docusaurus provides a response table of contents automatically.

### PR DESCRIPTION
**Pull request by kleinschmidtj**
Removes the custom Table of Contents from markdown files. Docusaurus provides TOC out of the box.

Closes #254

### CODE REVIEW

**Comment by rpdelaney** [comment]
Is there any way we can prevent it from being re-introduced?

**Comment by rogeruiz** [comment]
@rpdelaney that's a great question? I can't think of anything off the top of my head that isn't searching through files automatically and then exiting non-zero in CI.

**Comment by rpdelaney** [comment]
I'd look into rolling a [pygrep pre-commit hook](https://pre-commit.com/#pygrep). Something like this?

```yaml
-   id: no-mdformat-toc
    name: Block mdformat TOCs
    description: This hook prevents introducing mdformat TOCS, since Docusaurus generates its own.
    entry: mdformat-toc start
    language: pygrep
    types: [markdown]
```

**Comment by rogeruiz** [comment]
not sure @rpdelaney but I trust your direction here. Thank you! Also, this would be best run on PRs rather than locally, but I'm open to either or both.

**Comment by rpdelaney** [comment]
For some reason I can't push to this branch, so here's a patch someone can apply:

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index d26ec84..bca926e 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -27,3 +27,12 @@ repos:
     rev: v1.1.0
     hooks:
       - id: circleci-validate
+
+  - repo: local
+    hooks:
+      - id: no-mdformat-toc
+        name: Block mdformat TOCs
+        description: This hook prevents introducing mdformat TOCs, since Docusaurus generates its own.
+        entry: mdformat-toc start
+        language: pygrep
+        types: [markdown]
```

Demo:

```console
$ git diff --cached
diff --git c/CONTRIBUTING.md i/CONTRIBUTING.md
index 191b629..8a9d13a 100644
--- c/CONTRIBUTING.md
+++ i/CONTRIBUTING.md
@@ -1,3 +1,5 @@
+<!-- mdformat-toc start --slug=github --no-anchors --maxlevel=6 --minlevel=2 -->
+
 # Contributing to the playbook

 ## What
$ git commit
$ git commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/ryan/.cache/pre-commit/patch1667586637-71750.
Check for merge conflicts................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Detect Private Key.......................................................Passed
Trim Trailing Whitespace.................................................Passed
markdownlint.............................................................Passed
mdformat.................................................................Failed
- hook id: mdformat
- files were modified by this hook
Validate CircleCI config yaml........................(no files to check)Skipped
Block mdformat TOCs......................................................Failed
- hook id: no-mdformat-toc
- exit code: 1

CONTRIBUTING.md:1:<!-- mdformat-toc start --slug=github --no-anchors --maxlevel=6 --minlevel=2 -->

[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
[INFO] Restored changes from /Users/ryan/.cache/pre-commit/patch1667586637-71750.
```

**Comment by rpdelaney** [comment]
@rogeruiz @kleinschmidtj See above ☝️ Are you able to apply that patch to this branch? Still don't know why I can't just push to this branch myself

**Comment by rogeruiz** [comment]
What does your remote URL look like for this repository @rpdelaney? Are you using HTTPS or SSH?

**Pull request merged**
