### PR TITLE
Add Python content to eng playbook

### PR DESCRIPTION
**Pull request by jim**
This is a distillation of discussions we've had and research I've done about how to best write Python in our projects.

### CODE REVIEW

**Comment by rpdelaney** [comment]
AHH I was drafting something like this :)

**Comment by jim** [comment]
@rpdelaney I would love to see what you've come up with.

**Comment by rpdelaney** [comment]
From the looks of it I did a very similar structural change like you did, and then added some more opinionated stuff that could (potentially) be controversial but I think is nonetheless correct :-) With that in mind I suggest the thing to do here is merge in your PR and I'll adapt my additions into a follow-on for separate discussion. What do you think?

**Comment by jim** [comment]
@rpdelaney Sounds good. I converted this to a real PR so it can be reviewed.

**Pull request merged**
